[package]
name = "tic-tac-toe"
version = "0.1.0"
edition = "2024"

[dependencies]
# phf = "0.13.1"
rand = "0.9.2"
gtk = { version = "0.10.2", package = "gtk4", features = ["v4_18"] }
adw = { package = "libadwaita", version = "=0.8.0", features = ["v1_7"] }

[build-dependencies]
glob = "0.3"
